### ISSUE TITLE
Update document

### ISSUE THREAD

**Issue by lijinhong11** [Maxlego08/zMenu#15]
The document looks like it doesn't sync with the latest version.
And there are some mistakes that need to be fixed.
Mistakes below:  

1.
![{652E0B84-E502-40db-A4D2-6B31DCCFECE6}](https://github.com/Maxlego08/zMenu/assets/62691956/a4506cb8-0910-47fa-b392-5d7dff8fa96c)
There isn't RBG color, it is RGB colors, and you can add another example to show the ARGB (Alpha, Red, Green, Blue) colors format.

2.
![{DF41CE37-556B-42c9-8D12-1A7CC5EBCB77}](https://github.com/Maxlego08/zMenu/assets/62691956/8c0c0118-7cb5-4d75-afe0-7e290605e0b0)
You missed the Firework, Banner and the leather color armor

3.
![{12A4EC93-8486-4859-A6D9-9BF9CD40AC70}](https://github.com/Maxlego08/zMenu/assets/62691956/fce7a427-a62b-4d0d-8155-ca489609d1c7)
Change 'fakeColors' to 'fadeColors', and I have fixed in code in #9

Optimize the reading experience:
![{C32992C8-9EE1-44d6-8D5D-93E69CF588EE}](https://github.com/Maxlego08/zMenu/assets/62691956/f47e4f8b-e437-46ff-b006-a579bca33fc5)
Recommend using line breaks to separate all options for each feature

**Comment by Maxlego08** [comment]
Thanks for the feedback, I improved the documentation!

**Comment by lijinhong11** [comment]
Thanks!
