### ISSUE TITLE
[Feature Request] Add support for Paper's AsyncChat

### ISSUE THREAD

**Issue by NoltoxGit** [Maxlego08/zMenu#33]
Hello,
Can you add the support for the Paper `AsyncChatEvent` and/or `AsyncChatDecorateEvent` in the configuration of your plugin please?
Because you're currently using an old listener: `org.bukkit.event.player.AsyncPlayerChatEvent`. 

Example for a new configuration:
```yml
# Use Paper's async Chat Event
use-async-chat: true/false
```

Thank you so much if you add this! :)

**Comment by lijinhong11** [comment]
where
