### ISSUE TITLE
About UpdateInterval

### ISSUE THREAD

**Issue by Mocousemoxx** [Maxlego08/zMenu#37]
Change the updateInterval detection to tick.

**Comment by alexey-va** [comment]
Changing it to ticks would probably break many existing configurations. Maybe make updateInterval accept double and convert it to ticks? like 0.05 -> 1 tick & 1 -> 20 ticks.

**Comment by Mocousemoxx** [comment]
Yes, updateInterval now only accepts int, which is 20 ticks, if you change it to double you can use less than 20 ticks.

**Comment by Maxlego08** [comment]
This has been changed to milliseconds
