### ISSUE TITLE
[BUG] Numbers saved in PlayerData are not Numbers after a restart.

### ISSUE THREAD

**Issue by RustyDagger** [Maxlego08/zMenu#59]
The title sums it up pretty well.

to recreate:
start the server and run zm players set <name> testing 0 10
to create a player data entry with a number stored.
confirm its a number with
zm players add <name> testing 2
it should make testing = 12

next save and stop the server

start the server and repeat the add command, this is where the plugin will error with a NumberFormat or such.

**Comment by Maxlego08** [comment]
Fixed
