### ISSUE TITLE
Support for oraxen items as a material

### ISSUE THREAD

**Issue by lucian929** [Maxlego08/zMenu#7]
Oraxen is a plugin which allows you to create custom items easily. Adding support would make it easier for Oraxen users to add their custom items to zMenu.

https://github.com/oraxen/oraxen

**Comment by Maxlego08** [comment]
You can already use custom items with the "custom model data"

**Comment by lucian929** [comment]
> You can already use custom items with the "custom model data"

This is true, however, this (in my experience) takes longer compared to working with plugins that have a native integration, since otherwise, you need to refer to the assigned modeldata number for each item.

**Comment by Maxlego08** [comment]
You can join my discord and create a post on the zmenu forum, so I send you directly the plugin to test
https://discord.gg/4yB2mjB
