### ISSUE TITLE
[Suggestion] add optional commands

### ISSUE THREAD

**Issue by Z3r0xh** [Maxlego08/zMenu#89]
It would be to do the following:

If you put only /warp only the zmenu menu will open

but if you put /warp shop it will take you directly to the essentials warp

With this what I am saying is being able to add optional values ​​that execute other customizable actions

**Comment by Maxlego08** [comment]
Hey, you can aleady do this: https://docs.zmenu.dev/configurations/commands
With action type you can define argument and run an action, like /essentials:ewarp shop %player% for example

**Comment by Z3r0xh** [comment]
> Hey, you can aleady do this: https://docs.zmenu.dev/configurations/commands With action type you can define argument and run an action, like /essentials:ewarp shop %player% for example

I can't find a way to make it optional.

If, for example, I only write /warp, only the menu will open

But if I write /warp shop, it does the essentials command.

Do you have any example so I can understand it? I have been checking the wiki but I can't get it, it always forces me to use the arguments and I can't make them optional

**Comment by Z3r0xh** [comment]
Would you have an example of how to do it? even if it's simple
