### ISSUE TITLE
commands: dont work anymore

### ISSUE THREAD

**Issue by CaesarGalahad** [Maxlego08/zMenu#90]
commands: dont work anymore. If you click on the item nothing happens.

INFO
server version purpur-2265 MC-1.21
zMenu version 1.0.3.3

**Comment by Maxlego08** [comment]
Plz provide more informations, logs, configuration, etc

**Comment by CaesarGalahad** [comment]
> Plz provide more informations, logs, configuration, etc

The console did not return any information 

config:
![image](https://github.com/user-attachments/assets/4e0becbc-5132-4f05-b2f3-7130daead914)

**Comment by Maxlego08** [comment]
Already fixed bug, i will update the file tomorow !
